# As the orchestration need is simple to declare,
# Service and ReplicationController yamls files are combined.
apiVersion: v1
kind: ReplicationController
metadata:
  name: shopfront-controller
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shopfront
    spec:
      containers:
      - image: eu.gcr.io/refined-algebra-215620/shopfront:v1
        imagePullPolicy: Always
        name: shopfront
        resources:
          requests:
            cpu: 50m
        ports:
        - containerPort: 8082
          name: http-server
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 15
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          periodSeconds: 2
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: shopfront
  namespace: default
  labels:
    app: shopfront
spec:
  type: NodePort
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: shopfront